timecard/urls.py
"""
Django プロジェクト timecard の URL ディスパッチャです。
"""
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('', RedirectView.as_view(url='/worktime/login/', permanent=False)),
    path('admin/', admin.site.urls),
    path('worktime/', include('worktime.urls')),
]

worktime/urls.py
"""
URL ディスパッチャです。
"""
from django.urls import path

from worktime.views import (PasswordChange, ReadmeView, TimeOffListView,
                            TimeOffRequestView, TimeOffStatusView,
                            TimeRecordCalendarView, TimeRecordSummaryView,
                            TimeRecordView, UserLogin, UserLogout,
                            api_record_summary, api_users_list,
                            time_off_accept, time_off_cancel)

# アプリケーション名
app_name = "worktime"

# URL パターン
urlpatterns = [
    path('login/', UserLogin.as_view(), name='login'),
    path('logout/', UserLogout.as_view(), name='logout'),
    path('password_change/', PasswordChange.as_view(), name='password_change'),
    path('time_off/status/', TimeOffStatusView.as_view(), name='time_off_status'),
    path('time_off/request/', TimeOffRequestView.as_view(), name='time_off_request'),
    path('time_off/list/', TimeOffListView.as_view(), name='time_off_list'),
    path('time_off/accept/', time_off_accept, name='time_off_accept'),
    path('time_off/cancel/', time_off_cancel, name='time_off_cancel'),
    path('record/', TimeRecordView.as_view(), name='record'),
    path('record/calendar/',
         TimeRecordCalendarView.as_view(),
         name='record_calendar'
         ),
    path('record/summary/', TimeRecordSummaryView.as_view(), name='record_summary'),
    path('readme/', ReadmeView.as_view(), name='readme'),
    path('api/users/list/', api_users_list, name='api_users_list'),
    path('api/record/summary/', api_record_summary, name='api_record_summary'),
]

worktime/forms.py
"""
フォームです。
"""
from django import forms
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm

from worktime.models import TimeOffPattern


class CustomAuthenticationForm(AuthenticationForm):
    """ログイン画面のフォーム

    Args:
        AuthenticationForm: 継承するフォーム
    """

    def __init__(self, *args, **kwargs):
        """初期化
        """
        super().__init__(*args, **kwargs)

        # Bootstrap 対応
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class CustomPasswordChangeForm(PasswordChangeForm):
    """パスワード変更画面のフォーム

    Args:
        PasswordChangeForm: 継承するフォーム
    """

    def __init__(self, *args, **kwargs):
        """初期化
        """
        super().__init__(*args, **kwargs)

        # Bootstrap 対応
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class TimeRecordForm(forms.Form):
    """打刻画面のフォーム

    Args:
        forms: 継承するフォーム
    """
    action = forms.CharField(widget=forms.HiddenInput)
    latitude = forms.CharField(widget=forms.HiddenInput, required=False)
    longitude = forms.CharField(widget=forms.HiddenInput, required=False)
    accuracy = forms.CharField(widget=forms.HiddenInput, required=False)
    ua = forms.CharField(widget=forms.HiddenInput, required=False)


class TimeOffListForm(forms.Form):
    """休暇承認画面のフォーム

    Args:
        forms: 継承するフォーム
    """
    pass


class TimeOffStatusForm(forms.Form):
    """休暇集計画面のフォーム

    Args:
        forms: 継承するフォーム
    """
    pass


class TimeOffRequestForm(forms.Form):
    """休暇申請画面のフォーム

    Args:
        forms: 継承するフォーム
    """
    request_date = forms.DateField(
        label='対象日', widget=forms.DateInput(attrs={"type": "date"})
    )
    pattern_id = forms.fields.ChoiceField(
        label='種別', required=True, widget=forms.widgets.Select
    )
    contact = forms.CharField(
        label='連絡欄', widget=forms.Textarea(attrs={'rows': '2'}), required=False
    )

    def __init__(self, *args, **kwargs):
        """初期化
        """
        super().__init__(*args, **kwargs)
        self.fields['pattern_id'].choices = [
            (obj.id, obj.display_name) for obj in TimeOffPattern.objects.all()
        ]

        # Bootstrap 対応
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class TimeRecordCalendarForm(forms.Form):
    """勤務表画面のフォーム

    Args:
        forms: 継承するフォーム
    """
    username = forms.CharField(required=False)


class TimeRecordSummaryForm(forms.Form):
    """勤務集計画面のフォーム

    Args:
        forms: 継承するフォーム
    """
    pass

worktime/views.py
"""
ビュー定義です。
"""
import datetime
from functools import wraps

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import AccessMixin, LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.db.models import Q
from django.http import HttpResponseForbidden
from django.http.response import JsonResponse
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from django.utils import dateformat
from django.views.generic import FormView, TemplateView

import timecard.settings
from worktime.forms import (CustomAuthenticationForm, CustomPasswordChangeForm,
                            TimeOffListForm, TimeOffRequestForm,
                            TimeOffStatusForm, TimeRecordCalendarForm,
                            TimeRecordForm, TimeRecordSummaryForm)
from worktime.models import TimeOffPattern, TimeOffRequest, TimeRecord
from worktime.queries import count_time_off_requests, get_monthly_records
from worktime.rules import summarize
from worktime.utils import (display_name, get_first_day_of_year, get_users,
                            get_year_range)


class StaffRequiredMixin(AccessMixin):
    """スタッフ権限を要求するミックスイン
    """

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_staff:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)


class UserLogin(LoginView):
    """ログイン画面のビュー
    """
    form_class = CustomAuthenticationForm
    template_name = 'worktime/auth_login.html'
    redirect_authenticated_user = True


class UserLogout(LogoutView):
    """ログアウト画面のビュー
    """
    pass


class PasswordChange(LoginRequiredMixin, PasswordChangeView):
    """パスワード変更画面のビュー
    """
    form_class = CustomPasswordChangeForm
    template_name = 'worktime/password_change.html'
    success_url = reverse_lazy('worktime:record')

    def form_valid(self, form):
        """バリデーション成功
        """
        messages.success(self.request, 'パスワードが更新されました')
        return super().form_valid(form)


class TimeRecordView(LoginRequiredMixin, FormView):
    """打刻画面のビュー
    """
    form_class = TimeRecordForm
    template_name = 'worktime/record.html'
    success_url = reverse_lazy('worktime:record')

    def get_context_data(self, *args, **kwargs):
        """コンテキストの返却
        """
        context = super().get_context_data(*args, **kwargs)
        context["is_enable_check_location"] = timecard.settings.ENABLE_CHECK_LOCATION
        context["is_enable_record_sound"] = timecard.settings.ENABLE_RECORD_SOUND
        context["is_enable_record_vibrate"] = timecard.settings.ENABLE_RECORD_VIBRATE
        context["display_name"] = display_name(self.request.user)
        context["recent"] = TimeRecord.objects.filter(
            username=self.request.user.username
        ).order_by("-date", "-time")[:10]
        context["actions"] = timecard.settings.RECORD_ACTIONS
        return context

    def string_to_float(self, string: str) -> float:
        """文字列を数値で取得します。

        Args:
            string (str): 文字列

        Returns:
            float: 数値
        """
        return float(string) if string else None

    def form_valid(self, form):
        """バリデーション成功
        """
        now = datetime.datetime.now()
        action = form.cleaned_data['action']
        TimeRecord.objects.create(
            date=now.date(),
            time=now.time(),
            username=self.request.user.username,
            action=action,
            latitude=self.string_to_float(form.cleaned_data['latitude']),
            longitude=self.string_to_float(form.cleaned_data['longitude']),
            accuracy=self.string_to_float(form.cleaned_data['accuracy']),
            ua=form.cleaned_data['ua'],
        )
        messages.success(
            self.request,
            timecard.settings.RECORD_ACTIONS.get(action) + 'の打刻が完了しました'
        )
        return super().form_valid(form)


class TimeOffListView(StaffRequiredMixin, FormView):
    """休暇承認画面のビュー
    """
    form_class = TimeOffListForm
    template_name = 'worktime/time_off_list.html'
    success_url = reverse_lazy('worktime:time_off_list')

    def get_context_data(self, *args, **kwargs):
        """コンテキストの返却
        """
        context = super().get_context_data(*args, **kwargs)
        records = TimeOffRequest.objects.filter(accepted=False).values(
            'id',
            'date',
            'username',
            'display_name',
            'created_at',
            'contact'
        ).order_by('date')
        entries = []
        for record in records:
            year = get_first_day_of_year(record['date']).year
            year_range = get_year_range(year)
            counts = count_time_off_requests(record['username'], year_range)
            entries.append({
                'id': record['id'],
                'year': year,
                'date': record['date'],
                'username': record['username'],
                'display_name': record['display_name'],
                'created_at': record['created_at'],
                'count': counts.get(record['display_name'], 0),
                'contact': record['contact']
            })
        context['entries'] = entries
        context['users'] = get_users(False)
        return context


class TimeOffStatusView(StaffRequiredMixin, FormView):
    """休暇集計画面のビュー
    """
    form_class = TimeOffStatusForm
    template_name = 'worktime/time_off_status.html'
    success_url = reverse_lazy('worktime:time_off_status')

    def get_context_data(self, *args, **kwargs):
        """コンテキストの返却
        """
        context = super().get_context_data(*args, **kwargs)
        today = datetime.datetime.today()
        first_day_of_year = get_first_day_of_year(today)
        context['year'] = int(self.request.GET.get(
            'year', first_day_of_year.year
        ))
        context['years'] = range(
            first_day_of_year.year - 9,
            first_day_of_year.year + 1
        )
        context['current_year'] = first_day_of_year.year
        context['entries'] = []
        display_names = []
        for id, name in get_users(True).items():
            counts = count_time_off_requests(
                id, get_year_range(context['year'])
            )
            for display_name in counts.keys():
                if not display_name in display_names:
                    display_names.append(display_name)
            if 0 < len(counts):
                context['entries'].append({
                    'id': id,
                    'name': name,
                    'counts': counts
                })
        context['display_names'] = sorted(display_names)
        return context


class TimeOffRequestView(LoginRequiredMixin, FormView):
    """休暇申請画面のビュー
    """
    form_class = TimeOffRequestForm
    template_name = 'worktime/time_off_request.html'
    success_url = reverse_lazy('worktime:time_off_request')

    def get_context_data(self, *args, **kwargs):
        """コンテキストの返却
        """
        context = super().get_context_data(*args, **kwargs)
        today = datetime.datetime.today()
        first_day_of_year = get_first_day_of_year(today)
        context["entries"] = TimeOffRequest.objects.filter(username=self.request.user.username).filter(
            Q(date__gte=first_day_of_year) | Q(accepted=False)
        ).distinct().order_by("date")
        context["counts"] = count_time_off_requests(
            self.request.user.username, get_year_range(first_day_of_year.year)
        )
        return context

    def form_valid(self, form):
        """バリデーション成功
        """
        request_date = form.cleaned_data['request_date']
        records = TimeOffRequest.objects.filter(
            date=request_date, username=self.request.user.username)
        if records.exists():
            form.add_error('request_date', '指定した日には既に申請が存在します')
            return self.form_invalid(form)
        pattern = TimeOffPattern.objects.get(
            id=form.cleaned_data['pattern_id']
        )
        TimeOffRequest.objects.create(
            date=request_date,
            username=self.request.user.username,
            display_name=pattern.display_name,
            contact=form.cleaned_data['contact'],
            attendance=pattern.attendance,
            begin=pattern.begin,
            end=pattern.end,
            leave=pattern.leave,
            back=pattern.back,
            accepted=False
        )
        messages.success(
            self.request,
            dateformat.format(request_date, 'Y/m/d (D)') +
            ' の ' + pattern.display_name + ' を申請しました'
        )
        return super().form_valid(form)


class TimeRecordCalendarView(LoginRequiredMixin, FormView):
    """勤務表画面のビュー
    """
    form_class = TimeRecordCalendarForm
    template_name = 'worktime/record_calendar.html'

    def get_context_data(self, **kwargs):
        """コンテキストの返却
        """
        context = super().get_context_data(**kwargs)
        if self.request.user.is_staff:
            context['username'] = self.request.GET.get(
                'username', self.request.user.username)
        else:
            context['username'] = self.request.user.username
        today = datetime.datetime.today()
        context['year'] = int(self.request.GET.get('year', today.year))
        context['month'] = int(self.request.GET.get('month', today.month))
        context['entries'] = get_monthly_records(
            context['username'], context['year'], context['month']
        )
        context['summary'] = summarize(context['entries'])
        context['users'] = get_users(False)
        return context

    def get_initial(self):
        """初期値の取得
        """
        initial = super().get_initial()
        initial['username'] = self.request.GET.get(
            'username', self.request.user.username
        )
        return initial

    def form_valid(self, form):

worktime/templates/worktime/auth_login.html
{% extends 'worktime/base.html' %}
{% block main %}
<style>
    .form-control {
        margin-top: 8px;
        margin-bottom: 8px;
    }
</style>
<div class="container text-center">
    <div class="row">
        <div class="col">
            <h2>ログイン</h2>
        </div>
    </div>
</div>
<div class="container">
    <div class="row justify-content-md-center">
        <div class="col-lg-5 col-md-8">
            <form action="{% url 'worktime:login' %}" method="post">
                {% csrf_token %}
                {% if next %}
                <input type="hidden" name="next" value="{{ next }}" />
                {% endif %}
                {% if form.non_field_errors %}
                <ul class="alert alert-danger list-unstyled">
                    {% for error in form.non_field_errors %}
                    <li>{{ error }}</li>
                    {% endfor %}
                </ul>
                {% endif %}
                <input type="hidden" name="redirect" value="{{ redirect }}">
                {% for field in form %}
                <div class="form-group">
                    <label class="col-6" for="{{ field.id_for_label }}">{{ field.label_tag }}</label>
                    {{ field }}
                    {{ field.errors }}
                </div>
                {% endfor %}
                <div class="form-group row">
                    <div class="col-sm">
                        <button type="submit" class="btn btn-primary btn-block">ログイン</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock main %}

worktime/templates/worktime/page_footer.html
<footer>
    <div class="container text-center no-print">
        <div class="row m-5">
            <div class="col">
                <span class="signature">Powered by <a href="{{ APP_SITE }}" target="_blank">{{ APP_NAME }}</a> {{ APP_VERSION }}</span>
            </div>
        </div>
    </div>
</footer>

worktime/templates/worktime/page_header.html
{% load static %}
<form id="logout_form" action="{% url 'worktime:logout' %}" method="post">
    {% csrf_token %}
</form>
<header>
    <nav class="navbar navbar-expand-lg bg-light fixed-top no-print">
        <div class="container-fluid">
            <a href="{% url 'worktime:record' %}"><img class="navbar-brand" style="height:45px;" src="{% static 'worktime/logo.svg' %}"></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <div class="navbar-nav">
                    <a class="nav-item nav-link" href="{% url 'worktime:record' %}">打刻</a>
                    <a class="nav-item nav-link" href="{% url 'worktime:record_calendar' %}">勤務表</a>
                    <a class="nav-item nav-link" href="{% url 'worktime:time_off_request' %}">休暇申請</a>
                    {% if user.is_staff %}
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">管理機能</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="{% url 'worktime:record_summary' %}">勤務集計</a>
                            <a class="dropdown-item" href="{% url 'worktime:time_off_list' %}">休暇承認</a>
                            <a class="dropdown-item" href="{% url 'worktime:time_off_status' %}">休暇集計</a>
                            <hr class="dropdown-divider">
                            <a class="dropdown-item" href="{% url 'admin:index' %}">システム管理</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
                <div class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <div class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">こんにちは {% if user.first_name or user.last_name %}{{ user.last_name }} {{ user.first_name }}{% else %}{{ user.get_username }}{% endif %} さん</a>
                        <div class="dropdown-menu dropdown-menu-end">
                            <a class="dropdown-item" href="{% url 'worktime:password_change' %}">パスワード変更</a>
                            <a class="dropdown-item" href="{% url 'worktime:readme' %}">使用方法</a>
                            <hr class="dropdown-divider">
                            <a class="dropdown-item" href="#" onclick="document.getElementById('logout_form').submit();">ログアウト</a>
                        </div>
                    </div>
                    {% else %}
                    <div class="nav-item">
                        <a class="btn btn-success btn-sm" href="{% url 'worktime:login' %}">ログイン</a>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>

worktime/templates/worktime/record_summary.html
{% extends 'worktime/base.html' %}
{% load static %}
{% block title %}{{ year }}年{{ month }}月 | {{ block.super }}{% endblock title %}
{% block extra_head %}
<link href="{% static 'worktime/print.css' %}" rel="stylesheet">
<link href="{% static 'worktime/sortable_table.css' %}" rel="stylesheet">
<script src="{% static 'worktime/sortable_table.js' %}"></script>
{% endblock %}
{% block main %}
<div class="container text-center">
    <div class="row">
        <div class="col mb-3">
            <h2>{{ year }}年{{ month }}月</h2>
        </div>
    </div>
</div>
<div class="container no-print">
    <div class="row justify-content-center text-center">
        <div class="col mb-3">
            <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                <button class="btn btn-outline-secondary" onclick="show_calendar(-12)">&lt; 年</button>
                <button class="btn btn-outline-secondary" onclick="show_calendar(-1)">&lt; 月</button>
                <button class="btn btn-outline-secondary" onclick="show_calendar(0)">今月</button>
                <button class="btn btn-outline-secondary" onclick="show_calendar(1)">月 &gt;</button>
                <button class="btn btn-outline-secondary" onclick="show_calendar(12)">年 &gt;</button>
            </div>
            <div class="btn-group btn-group-sm" role="group" aria-label="Small button group">
                <button class="btn btn-outline-secondary" onclick="window.print();">印刷</button>
                <button class="btn btn-outline-secondary" onclick="download_csv();">ダウンロード</button>
            </div>
        </div>
    </div>
</div>
<div id="running" class="text-secondary text-center my-5 no-print">
    <div class="spinner-border spinner-border-sm" role="status"></div>
    <span id="progress">0 %</span>
</div>
<div class="container mb-3">
    <div class="table-responsive">
        <table id="summary" class="table align-middle text-nowrap text-center d-none">
            <thead>
                <tr>
                    <th rowspan="2">合計</th>
                    <th rowspan="2">エラー</th>
                    <th rowspan="2">承認待ち</th>
                    <th rowspan="2">遅刻・早退</th>
                    <th colspan="3"><span class="inline-help" data-bs-title="早出と残業の合計時間です">時間外</span></th>
                </tr>
                <tr>
                    <th>30 以上</th>
                    <th>45 以上</th>
                    <th>60 以上</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                <tr>
                    <td id="summary_count">-</td>
                    <td id="summary_errors">-</td>
                    <td id="summary_not_accepted">-</td>
                    <td id="summary_behind">-</td>
                    <td id="summary_overtime_1">-</td>
                    <td id="summary_overtime_2">-</td>
                    <td id="summary_overtime_3">-</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
<div class="container mb-3">
    <div class="table-responsive">
        <table id="entries" class="table table-hover table-bordered text-nowrap text-center sortable d-none">
            <thead>
                <tr class="table-dark">
                    <th>氏名</th>
                    <th>エラー</th>
                    <th>出勤日</th>
                    <th>休暇申請</th>
                    <th>遅刻・早退</th>
                    <th>早出</th>
                    <th>残業</th>
                </tr>
            </thead>
            <tbody class="table-group-divider"></tbody>
        </table>
    </div>
</div>
<script>
    const year = Number("{{ year }}")
    const month = Number("{{ month }}")
    let entries = [];
    function create_rows() {
        let rows = [[
            'ID',
            '氏名',
            '年',
            '月',
            '日数(日)',
            '営業日(日)',
            '出勤日(日)',
            '休暇申請(合計)(回)',
            '休暇申請(承認待ち)(回)',
            '遅刻早退(回)',
            '遅刻早退(時間)',
            '遅刻早退(分)',
            '早出(回)',
            '早出(時間)',
            '早出(分)',
            '残業(回)',
            '残業(時間)',
            '残業(分)',
            'エラー(個)'
        ]];
        for (let entry of entries) {
            let summary = entry.summary;
            rows.push([
                '"' + entry.id + '"',
                '"' + entry.name + '"',
                year,
                month,
                summary.days,
                summary.attendance_days,
                summary.work_days,
                summary.time_off_count,
                summary.time_off_not_yet_accepted_count,
                summary.behind_count,
                summary.behind_hours,
                summary.behind_minutes,
                summary.early_count,
                summary.early_hours,
                summary.early_minutes,
                summary.overtime_count,
                summary.overtime_hours,
                summary.overtime_minutes,
                summary.errors
            ])
        }
        return rows;
    }
    function download_csv() {
        const now = new Date();
        let current = (now.getFullYear()).toString();
        current += (now.getMonth() + 1).toString().padStart(2, '0');
        current += (now.getDate()).toString().padStart(2, '0');
        const bom = new Uint8Array([0xef, 0xbb, 0xbf])
        const data = create_rows().map(columns => columns.join(',')).join('\n')
        const filename = 'summary-' + year.toString().padStart(4, '0') + '-' + month.toString().padStart(2, '0') + '-' + current + '.csv';
        download(new Blob([bom, data]), filename, { type: 'text/csv' });
    }
    function download(blob, filename, options) {
        const link = document.createElement('a');
        link.download = filename;
        link.href = URL.createObjectURL(blob, options);
        link.click();
        URL.revokeObjectURL(link.href)
    }
    function show_calendar(delta) {
        const months = year * 12 + (month - 1) + delta;
        const now = new Date();
        let n_year, n_month;
        if (delta == 0) {
            n_year = now.getFullYear();
            n_month = now.getMonth() + 1;
        } else {
            n_year = Math.floor(months / 12);
            n_month = months % 12 + 1;
        }
        location.href = "{% url 'worktime:record_summary' %}?year=" + n_year + "&month=" + n_month
    }
    async function load_entries() {
        const progress = document.getElementById('progress')
        const users_response = await fetch("{% url 'worktime:api_users_list' %}");
        if (!users_response.ok) {
            throw new Error('Response error');
        }
        const users = await users_response.json();
        for (let id in users) {
            const response = await fetch("{% url 'worktime:api_record_summary' %}?id=" + id + "&year=" + year + "&month=" + month);
            if (!response.ok) {
                throw new Error('Response error');
            }
            const summary = await response.json();
            entries.push({ id: id, name: users[id], summary: summary });
            progress.innerText = Math.round(entries.length / Object.keys(users).length * 100 / 5) * 5 + ' %';
        }
        const tbody = document.getElementById("entries").getElementsByTagName('tbody')[0];
        let summary_count = 0;
        let summary_errors = 0;
        let summary_not_accepted = 0;
        let summary_behind = 0;
        let summary_overtime_1 = 0;
        let summary_overtime_2 = 0;
        let summary_overtime_3 = 0;
        for (let entry of entries) {
            let summary = entry['summary']
            let row = tbody.insertRow();
            const cell1 = document.createElement('th'); row.appendChild(cell1);
            const cell2 = row.insertCell(1);
            const cell3 = row.insertCell(2);
            const cell4 = row.insertCell(3);
            const cell5 = row.insertCell(4);
            const cell6 = row.insertCell(5);
            const cell7 = row.insertCell(6);
            cell1.innerHTML = "<a href=\"{% url 'worktime:record_calendar' %}?username=" + entry.id + "&year=" + year + "&month=" + month + "\">" + entry.name + "</a>";
            cell1.setAttribute("data-sort", entry.name);
            cell2.innerHTML = 0 < summary.errors ? summary.errors + ' 個' : '';
            cell2.setAttribute("data-sort", summary.errors);
            cell3.innerHTML = 0 < summary.work_days ? summary.work_days + ' 日' : '';
            cell3.setAttribute("data-sort", summary.work_days);
            cell4.innerHTML = 0 < summary.time_off_count ? summary.time_off_count + ' 回' + (0 < summary.time_off_not_yet_accepted_count ? ' (承認待ち)' : '') : '';
            cell4.setAttribute("data-sort", summary.time_off_count);
            cell5.innerHTML = 0 < summary.behind_count ? summary.behind_count + ' 回 (' + summary.behind_minutes.toLocaleString() + ' 分)' : '';
            cell5.setAttribute("data-sort", summary.behind_count);
            cell6.innerHTML = 0 < summary.early_minutes ? summary.early_hours + ' 時間' : '';
            cell6.setAttribute("data-sort", summary.early_minutes);
            cell7.innerHTML = 0 < summary.overtime_minutes ? summary.overtime_hours + ' 時間' : '';
            cell7.setAttribute("data-sort", summary.overtime_minutes);
            summary_count++;
            if (0 < summary.errors) summary_errors++;
            if (0 < summary.time_off_not_yet_accepted_count) summary_not_accepted++;
            if (0 < summary.behind_count) summary_behind++;
            let overtime = Number(summary.early_hours) + Number(summary.overtime_hours);
            if (60 <= overtime) {
                summary_overtime_3++;
            } else if (45 <= overtime) {
                summary_overtime_2++;
            } else if (30 <= overtime) {
                summary_overtime_1++;
            }
        }
        if (0 < summary_count) document.getElementById('summary_count').innerText = summary_count + ' 人';
        if (0 < summary_errors) document.getElementById('summary_errors').innerText = summary_errors + ' 人';
        if (0 < summary_not_accepted) document.getElementById('summary_not_accepted').innerText = summary_not_accepted + ' 人';
        if (0 < summary_behind) document.getElementById('summary_behind').innerText = summary_behind + ' 人';
        if (0 < summary_overtime_1) document.getElementById('summary_overtime_1').innerText = summary_overtime_1 + ' 人';
        if (0 < summary_overtime_2) document.getElementById('summary_overtime_2').innerText = summary_overtime_2 + ' 人';
        if (0 < summary_overtime_3) document.getElementById('summary_overtime_3').innerText = summary_overtime_3 + ' 人';
        document.getElementById("running").classList.add("d-none");
        document.getElementById("summary").classList.remove("d-none");
        document.getElementById("entries").classList.remove("d-none");
    }
    window.addEventListener('load', load_entries);
</script>
{% endblock main %}